name: "reports to Codecov"

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: CloudArmor/PyAlgorithms
